# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'landing_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 854)
        MainWindow.setStyleSheet("margin:0;\n"
"padding:0;\n"
"background:#FFFFFF;")
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame.setStyleSheet("background:#0BDABF;\n"
"margin:0;\n"
"padding:0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboardBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dashboardBtn.setFont(font)
        self.dashboardBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboardBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.dashboardBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Images/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboardBtn.setIcon(icon)
        self.dashboardBtn.setIconSize(QtCore.QSize(40, 40))
        self.dashboardBtn.setObjectName("dashboardBtn")
        self.verticalLayout.addWidget(self.dashboardBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.manageUsersBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manageUsersBtn.setFont(font)
        self.manageUsersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageUsersBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.manageUsersBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/Images/man-line-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageUsersBtn.setIcon(icon1)
        self.manageUsersBtn.setIconSize(QtCore.QSize(40, 40))
        self.manageUsersBtn.setObjectName("manageUsersBtn")
        self.verticalLayout.addWidget(self.manageUsersBtn)
        self.manageServicesBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manageServicesBtn.setFont(font)
        self.manageServicesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageServicesBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.manageServicesBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Images/booking room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageServicesBtn.setIcon(icon2)
        self.manageServicesBtn.setIconSize(QtCore.QSize(40, 40))
        self.manageServicesBtn.setObjectName("manageServicesBtn")
        self.verticalLayout.addWidget(self.manageServicesBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.manageBookingBtn_2 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manageBookingBtn_2.setFont(font)
        self.manageBookingBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageBookingBtn_2.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.manageBookingBtn_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/Images/magnifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageBookingBtn_2.setIcon(icon3)
        self.manageBookingBtn_2.setIconSize(QtCore.QSize(40, 40))
        self.manageBookingBtn_2.setObjectName("manageBookingBtn_2")
        self.verticalLayout.addWidget(self.manageBookingBtn_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.managePaymentsBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.managePaymentsBtn.setFont(font)
        self.managePaymentsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.managePaymentsBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.managePaymentsBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/Images/generate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.managePaymentsBtn.setIcon(icon4)
        self.managePaymentsBtn.setIconSize(QtCore.QSize(40, 40))
        self.managePaymentsBtn.setObjectName("managePaymentsBtn")
        self.verticalLayout.addWidget(self.managePaymentsBtn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout.addWidget(self.frame_12)
        self.gridLayout.addWidget(self.frame_4, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_3.setStyleSheet("color:white;\n"
"background:#0BDABF;\n"
"padding:0px;\n"
"border:none;\n"
"text-align:cneter;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.frame_3, 3, 0, 1, 1)
        self.navBar = QtWidgets.QPushButton(self.frame)
        self.navBar.setMinimumSize(QtCore.QSize(50, 50))
        self.navBar.setMaximumSize(QtCore.QSize(50, 50))
        self.navBar.setStyleSheet("border:none;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/Images/icons8-hamburger-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navBar.setIcon(icon5)
        self.navBar.setIconSize(QtCore.QSize(50, 50))
        self.navBar.setObjectName("navBar")
        self.gridLayout.addWidget(self.navBar, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("text-align:left;\n"
"color:white;\n"
"border:none;\n"
"margin:0;\n"
"margin-top:20px;\n"
"padding:0;")
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(1)
        self.label.setIndent(-3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Dashboard = QtWidgets.QWidget()
        self.Dashboard.setObjectName("Dashboard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Dashboard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Dashboard)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_15 = QtWidgets.QFrame(self.Dashboard)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(180, 140))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_5.setStyleSheet("background:#F2F2F2;\n"
"border-radius:15px;\n"
"color:black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(180, 140))
        self.frame_6.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(180, 140))
        self.frame_8.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_8, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_15, 0, QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.Dashboard)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.frame_7 = QtWidgets.QFrame(self.Dashboard)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_64 = QtWidgets.QFrame(self.frame_7)
        self.frame_64.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_64)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_51 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: grey;")
        self.label_51.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 7, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color:#48ACAC")
        self.label_53.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 5, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color:#48ACAC")
        self.label_50.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 5, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_64)
        self.label_43.setMinimumSize(QtCore.QSize(0, 20))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color:#48ACAC")
        self.label_43.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 6, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.frame_64)
        self.label_52.setMinimumSize(QtCore.QSize(0, 20))
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: grey;")
        self.label_52.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 8, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color:#48ACAC;\n"
"image: url(:/Icons/Icons/icons8-scroll-down-50.png);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 7, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: grey;")
        self.label_54.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 7, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color:black")
        self.label_45.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 3, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:#48ACAC;\n"
"image: url(:/Icons/Icons/icons8-scroll-up-50.png);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 5, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_64)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #48ACAC;")
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 4, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_64, 0, 1, 3, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_56 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: grey;")
        self.label_56.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_56.setObjectName("label_56")
        self.gridLayout_11.addWidget(self.label_56, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.lblSalePerDay_2 = QtWidgets.QLabel(self.frame_11)
        self.lblSalePerDay_2.setMinimumSize(QtCore.QSize(200, 140))
        self.lblSalePerDay_2.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.lblSalePerDay_2.setText("")
        self.lblSalePerDay_2.setObjectName("lblSalePerDay_2")
        self.gridLayout_11.addWidget(self.lblSalePerDay_2, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_11, 2, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_55 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: grey;")
        self.label_55.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_55.setObjectName("label_55")
        self.gridLayout_10.addWidget(self.label_55, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.lblSalePerDay = QtWidgets.QLabel(self.frame_10)
        self.lblSalePerDay.setMinimumSize(QtCore.QSize(200, 140))
        self.lblSalePerDay.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.lblSalePerDay.setText("")
        self.lblSalePerDay.setObjectName("lblSalePerDay")
        self.gridLayout_10.addWidget(self.lblSalePerDay, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_10, 0, 0, 2, 1)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.Dashboard)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.Dashboard)
        self.manageStaffPage = QtWidgets.QWidget()
        self.manageStaffPage.setObjectName("manageStaffPage")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.manageStaffPage)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_13 = QtWidgets.QFrame(self.manageStaffPage)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_5 = QtWidgets.QLabel(self.frame_16)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_16)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_15.addWidget(self.lineEdit_3, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_15.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_15.addWidget(self.lineEdit_5, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_16)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 70))
        self.comboBox.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_15.addWidget(self.comboBox, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_2 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_15.addWidget(self.pushButton_2, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_16)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 5, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_16)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_15.addWidget(self.tableWidget, 6, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_3 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_15.addWidget(self.pushButton_3, 7, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_4 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_15.addWidget(self.pushButton_4, 7, 1, 1, 1)
        self.gridLayout_14.addWidget(self.frame_16, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.manageStaffPage)
        self.manageServicePage = QtWidgets.QWidget()
        self.manageServicePage.setObjectName("manageServicePage")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.manageServicePage)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_17 = QtWidgets.QFrame(self.manageServicePage)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_16.addWidget(self.frame_18, 9, 1, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_16.addWidget(self.frame_19, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_5 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_16.addWidget(self.pushButton_5, 11, 0, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_17)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_16.addWidget(self.tableWidget_2, 13, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_6 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_16.addWidget(self.pushButton_6, 14, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_7 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_16.addWidget(self.pushButton_7, 14, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_17)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_16.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_16.addWidget(self.lineEdit_8, 7, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_17)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_16.addWidget(self.label_16, 12, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_16.addWidget(self.lineEdit_6, 5, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame_17)
        self.textEdit.setMaximumSize(QtCore.QSize(500, 100))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_16.addWidget(self.textEdit, 9, 0, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.frame_17)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_16.addWidget(self.frame_25, 6, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame_17)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_16.addWidget(self.frame_26, 8, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_17, 0, 1, 2, 1)
        self.frame_14 = QtWidgets.QFrame(self.manageServicePage)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_13.addWidget(self.frame_14, 0, 2, 1, 1)
        self.frame_40 = QtWidgets.QFrame(self.manageServicePage)
        self.frame_40.setMaximumSize(QtCore.QSize(400, 110))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_13.addWidget(self.frame_40, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.manageServicePage)
        self.manageBookingPage = QtWidgets.QWidget()
        self.manageBookingPage.setObjectName("manageBookingPage")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.manageBookingPage)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_20 = QtWidgets.QFrame(self.manageBookingPage)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_17.addWidget(self.lineEdit_9, 4, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_17.addWidget(self.lineEdit_7, 4, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("border:none;\n"
"border-bottom: 2px solid black;")
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_17.addWidget(self.dateEdit, 6, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_20)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_17.addWidget(self.comboBox_2, 8, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_8 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_8:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_17.addWidget(self.pushButton_8, 8, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_17.addWidget(self.label_20, 9, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_9 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_9:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_17.addWidget(self.pushButton_9, 11, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid black;")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_17.addWidget(self.dateEdit_2, 6, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_10 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_10:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_17.addWidget(self.pushButton_10, 11, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_20)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_17.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_20)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_17.addWidget(self.label_19, 2, 0, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_20)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_17.addWidget(self.tableWidget_3, 10, 0, 1, 2)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_17.addWidget(self.frame_21, 1, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_17.addWidget(self.frame_22, 3, 0, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.frame_20)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_17.addWidget(self.frame_23, 7, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.frame_20)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_17.addWidget(self.frame_24, 5, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_20, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.manageBookingPage)
        self.managePaymentsPage = QtWidgets.QWidget()
        self.managePaymentsPage.setObjectName("managePaymentsPage")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.managePaymentsPage)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_27 = QtWidgets.QFrame(self.managePaymentsPage)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_21 = QtWidgets.QLabel(self.frame_27)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_19.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_27)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_19.addWidget(self.label_22, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_19.addWidget(self.lineEdit_10, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_19.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_19.addWidget(self.lineEdit_12, 3, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_27)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 70))
        self.comboBox_3.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout_19.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_11 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_11:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_19.addWidget(self.pushButton_11, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_27)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_19.addWidget(self.label_23, 5, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_27)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_4.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_4.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_19.addWidget(self.tableWidget_4, 6, 0, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_12 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_12:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_19.addWidget(self.pushButton_12, 7, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("/* Normal state styling */\n"
"QPushButton#pushButton_13 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#pushButton_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#pushButton_13:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_19.addWidget(self.pushButton_13, 7, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frame_27, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.managePaymentsPage)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.navBar.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Inn\n"
"Sync"))
        self.label_3.setText(_translate("MainWindow", "Dashboard"))
        self.label_14.setText(_translate("MainWindow", "750"))
        self.label_9.setText(_translate("MainWindow", "Total Users"))
        self.label_10.setText(_translate("MainWindow", "Active Users"))
        self.label_13.setText(_translate("MainWindow", "500"))
        self.label_11.setText(_translate("MainWindow", "Kicked Users"))
        self.label_12.setText(_translate("MainWindow", "150"))
        self.label_4.setText(_translate("MainWindow", "Market Place"))
        self.label_51.setText(_translate("MainWindow", "Worst Selling"))
        self.label_53.setText(_translate("MainWindow", "312"))
        self.label_50.setText(_translate("MainWindow", "Best Selling"))
        self.label_43.setText(_translate("MainWindow", "Sunday"))
        self.label_52.setText(_translate("MainWindow", "Friday"))
        self.label_54.setText(_translate("MainWindow", "123"))
        self.label_45.setText(_translate("MainWindow", "Sales"))
        self.label_18.setText(_translate("MainWindow", "Calculated in last 7 days"))
        self.label_56.setText(_translate("MainWindow", "Worst Selling"))
        self.label_55.setText(_translate("MainWindow", "Worst Selling"))
        self.label_5.setText(_translate("MainWindow", "Manage Staff"))
        self.label_7.setText(_translate("MainWindow", "Add Users:"))
        self.lineEdit_3.setText(_translate("MainWindow", "Name"))
        self.lineEdit_4.setText(_translate("MainWindow", "Password"))
        self.lineEdit_5.setText(_translate("MainWindow", "Email"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Role"))
        self.pushButton_2.setText(_translate("MainWindow", "Add User"))
        self.label_8.setText(_translate("MainWindow", "Add Users:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_4.setText(_translate("MainWindow", "Update"))
        self.pushButton_5.setText(_translate("MainWindow", "Add User"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        self.pushButton_6.setText(_translate("MainWindow", "Delete"))
        self.pushButton_7.setText(_translate("MainWindow", "Update"))
        self.label_6.setText(_translate("MainWindow", "Manage Service"))
        self.label_15.setText(_translate("MainWindow", "Add Service:"))
        self.lineEdit_8.setText(_translate("MainWindow", "Email"))
        self.label_16.setText(_translate("MainWindow", "All Services"))
        self.lineEdit_6.setText(_translate("MainWindow", "Name"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Description</span></p></body></html>"))
        self.lineEdit_9.setText(_translate("MainWindow", "Room Number"))
        self.lineEdit_7.setText(_translate("MainWindow", "Name"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Role"))
        self.pushButton_8.setText(_translate("MainWindow", "Add Booking"))
        self.label_20.setText(_translate("MainWindow", "Add Users:"))
        self.pushButton_9.setText(_translate("MainWindow", "Delete"))
        self.pushButton_10.setText(_translate("MainWindow", "Update"))
        self.label_17.setText(_translate("MainWindow", "Manage Booking"))
        self.label_19.setText(_translate("MainWindow", "Add Booking:"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        self.label_21.setText(_translate("MainWindow", "Manage Payments"))
        self.label_22.setText(_translate("MainWindow", "Add Payment:"))
        self.lineEdit_10.setText(_translate("MainWindow", "Name"))
        self.lineEdit_11.setText(_translate("MainWindow", "Password"))
        self.lineEdit_12.setText(_translate("MainWindow", "Email"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Role"))
        self.pushButton_11.setText(_translate("MainWindow", "Add User"))
        self.label_23.setText(_translate("MainWindow", "Add Users:"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        self.pushButton_12.setText(_translate("MainWindow", "Delete"))
        self.pushButton_13.setText(_translate("MainWindow", "Update"))
import resource_rc
