# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerLandingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 854)
        MainWindow.setStyleSheet("margin:0;\n"
"padding:0;\n"
"background:#FFFFFF;")
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame.setStyleSheet("background:#0BDABF;\n"
"margin:0;\n"
"padding:0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboardBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dashboardBtn.setFont(font)
        self.dashboardBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboardBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.dashboardBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Images/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboardBtn.setIcon(icon)
        self.dashboardBtn.setIconSize(QtCore.QSize(40, 40))
        self.dashboardBtn.setObjectName("dashboardBtn")
        self.verticalLayout.addWidget(self.dashboardBtn)
        self.manageUsersBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manageUsersBtn.setFont(font)
        self.manageUsersBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageUsersBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.manageUsersBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/Images/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageUsersBtn.setIcon(icon1)
        self.manageUsersBtn.setIconSize(QtCore.QSize(50, 50))
        self.manageUsersBtn.setObjectName("manageUsersBtn")
        self.verticalLayout.addWidget(self.manageUsersBtn)
        self.manageRoomBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manageRoomBtn.setFont(font)
        self.manageRoomBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageRoomBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.manageRoomBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Images/booking room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageRoomBtn.setIcon(icon2)
        self.manageRoomBtn.setIconSize(QtCore.QSize(40, 40))
        self.manageRoomBtn.setObjectName("manageRoomBtn")
        self.verticalLayout.addWidget(self.manageRoomBtn)
        self.manageSerices = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.manageSerices.setFont(font)
        self.manageSerices.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manageSerices.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.manageSerices.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/Images/icons8-service-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageSerices.setIcon(icon3)
        self.manageSerices.setIconSize(QtCore.QSize(40, 40))
        self.manageSerices.setObjectName("manageSerices")
        self.verticalLayout.addWidget(self.manageSerices)
        self.backupDatabaseNavigate = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backupDatabaseNavigate.setFont(font)
        self.backupDatabaseNavigate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backupDatabaseNavigate.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.backupDatabaseNavigate.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/Images/icons8-backup-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backupDatabaseNavigate.setIcon(icon4)
        self.backupDatabaseNavigate.setIconSize(QtCore.QSize(40, 40))
        self.backupDatabaseNavigate.setObjectName("backupDatabaseNavigate")
        self.verticalLayout.addWidget(self.backupDatabaseNavigate)
        self.showGuestFeedback = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showGuestFeedback.setFont(font)
        self.showGuestFeedback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showGuestFeedback.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.showGuestFeedback.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/Images/icons8-feedback-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showGuestFeedback.setIcon(icon5)
        self.showGuestFeedback.setIconSize(QtCore.QSize(40, 40))
        self.showGuestFeedback.setObjectName("showGuestFeedback")
        self.verticalLayout.addWidget(self.showGuestFeedback)
        self.profilePageBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profilePageBtn.setFont(font)
        self.profilePageBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profilePageBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.profilePageBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/Images/man-line-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profilePageBtn.setIcon(icon6)
        self.profilePageBtn.setIconSize(QtCore.QSize(40, 40))
        self.profilePageBtn.setObjectName("profilePageBtn")
        self.verticalLayout.addWidget(self.profilePageBtn)
        self.logoutBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logoutBtn.setFont(font)
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #0BDABF;\n"
"    padding: 15px;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16E2CB;\n"
"}\n"
"")
        self.logoutBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/Images/logoutImage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutBtn.setIcon(icon7)
        self.logoutBtn.setIconSize(QtCore.QSize(40, 40))
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout.addWidget(self.logoutBtn)
        self.gridLayout.addWidget(self.frame_4, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_3.setStyleSheet("color:white;\n"
"background:#0BDABF;\n"
"padding:0px;\n"
"border:none;\n"
"text-align:cneter;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.frame_3, 3, 0, 1, 1)
        self.navBar = QtWidgets.QPushButton(self.frame)
        self.navBar.setMinimumSize(QtCore.QSize(50, 50))
        self.navBar.setMaximumSize(QtCore.QSize(50, 50))
        self.navBar.setStyleSheet("border:none;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/Images/icons8-hamburger-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navBar.setIcon(icon8)
        self.navBar.setIconSize(QtCore.QSize(50, 50))
        self.navBar.setObjectName("navBar")
        self.gridLayout.addWidget(self.navBar, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("text-align:left;\n"
"color:white;\n"
"border:none;\n"
"margin:0;\n"
"margin-top:20px;\n"
"padding:0;")
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(1)
        self.label.setIndent(-3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Dashboard = QtWidgets.QWidget()
        self.Dashboard.setObjectName("Dashboard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Dashboard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Dashboard)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_15 = QtWidgets.QFrame(self.Dashboard)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(180, 140))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 140))
        self.frame_5.setStyleSheet("background:#F2F2F2;\n"
"border-radius:15px;\n"
"color:black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.totla_users_label = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totla_users_label.setFont(font)
        self.totla_users_label.setStyleSheet("text-align:center;\n"
"color:black;")
        self.totla_users_label.setObjectName("totla_users_label")
        self.gridLayout_4.addWidget(self.totla_users_label, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(180, 140))
        self.frame_6.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(180, 140))
        self.frame_8.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("text-align:center;\n"
"color:black;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_8, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_15, 0, QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.Dashboard)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.frame_7 = QtWidgets.QFrame(self.Dashboard)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_64 = QtWidgets.QFrame(self.frame_7)
        self.frame_64.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_64)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_51 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: grey;")
        self.label_51.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 7, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color:#48ACAC")
        self.label_53.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 5, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color:#48ACAC")
        self.label_50.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 5, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_64)
        self.label_43.setMinimumSize(QtCore.QSize(0, 20))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color:#48ACAC")
        self.label_43.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 6, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.frame_64)
        self.label_52.setMinimumSize(QtCore.QSize(0, 20))
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: grey;")
        self.label_52.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 8, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color:#48ACAC;\n"
"image: url(:/Icons/Icons/icons8-scroll-down-50.png);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 7, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: grey;")
        self.label_54.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 7, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color:black")
        self.label_45.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 3, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_64)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:#48ACAC;\n"
"image: url(:/Icons/Icons/icons8-scroll-up-50.png);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 5, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_64)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #48ACAC;")
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 4, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_64, 0, 1, 3, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_56 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: grey;")
        self.label_56.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_56.setObjectName("label_56")
        self.gridLayout_11.addWidget(self.label_56, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.lblSalePerDay_2 = QtWidgets.QLabel(self.frame_11)
        self.lblSalePerDay_2.setMinimumSize(QtCore.QSize(200, 140))
        self.lblSalePerDay_2.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.lblSalePerDay_2.setText("")
        self.lblSalePerDay_2.setObjectName("lblSalePerDay_2")
        self.gridLayout_11.addWidget(self.lblSalePerDay_2, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_11, 2, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_55 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: grey;")
        self.label_55.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_55.setObjectName("label_55")
        self.gridLayout_10.addWidget(self.label_55, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.lblSalePerDay = QtWidgets.QLabel(self.frame_10)
        self.lblSalePerDay.setMinimumSize(QtCore.QSize(200, 140))
        self.lblSalePerDay.setStyleSheet("background:#f5f5f5;\n"
"border-radius:15px;")
        self.lblSalePerDay.setText("")
        self.lblSalePerDay.setObjectName("lblSalePerDay")
        self.gridLayout_10.addWidget(self.lblSalePerDay, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_10, 0, 0, 2, 1)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.Dashboard)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.Dashboard)
        self.guestFeedbackPage = QtWidgets.QWidget()
        self.guestFeedbackPage.setObjectName("guestFeedbackPage")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.guestFeedbackPage)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.frame_53 = QtWidgets.QFrame(self.guestFeedbackPage)
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_53)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.frame_61 = QtWidgets.QFrame(self.frame_53)
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.gridLayout_26.addWidget(self.frame_61, 5, 0, 1, 2)
        self.frame_27 = QtWidgets.QFrame(self.frame_53)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_26.addWidget(self.frame_27, 7, 0, 1, 1)
        self.frame_59 = QtWidgets.QFrame(self.frame_53)
        self.frame_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.gridLayout_26.addWidget(self.frame_59, 1, 0, 1, 2)
        self.frame_60 = QtWidgets.QFrame(self.frame_53)
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.gridLayout_26.addWidget(self.frame_60, 2, 0, 2, 2)
        self.frame_58 = QtWidgets.QFrame(self.frame_53)
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.gridLayout_26.addWidget(self.frame_58, 4, 0, 1, 2)
        self.frame_12 = QtWidgets.QFrame(self.frame_53)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_26.addWidget(self.frame_12, 5, 3, 2, 1)
        self.frame_28 = QtWidgets.QFrame(self.frame_53)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_26.addWidget(self.frame_28, 10, 0, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.frame_53)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_26.addWidget(self.frame_35, 9, 1, 1, 2)
        self.frame_62 = QtWidgets.QFrame(self.frame_53)
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.gridLayout_26.addWidget(self.frame_62, 8, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.frame_53)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_26.addWidget(self.label_34, 11, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_53)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_26.addWidget(self.label_32, 0, 0, 1, 1)
        self.showAllUsersTable = QtWidgets.QTableWidget(self.frame_53)
        self.showAllUsersTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.showAllUsersTable.setObjectName("showAllUsersTable")
        self.showAllUsersTable.setColumnCount(4)
        self.showAllUsersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsersTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsersTable.setHorizontalHeaderItem(3, item)
        self.showAllUsersTable.horizontalHeader().setCascadingSectionResizes(False)
        self.showAllUsersTable.horizontalHeader().setSortIndicatorShown(False)
        self.showAllUsersTable.horizontalHeader().setStretchLastSection(False)
        self.showAllUsersTable.verticalHeader().setCascadingSectionResizes(False)
        self.showAllUsersTable.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_26.addWidget(self.showAllUsersTable, 12, 0, 1, 4)
        self.gridLayout_28.addWidget(self.frame_53, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.guestFeedbackPage)
        self.manageStaffPage = QtWidgets.QWidget()
        self.manageStaffPage.setObjectName("manageStaffPage")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.manageStaffPage)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_13 = QtWidgets.QFrame(self.manageStaffPage)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_29 = QtWidgets.QFrame(self.frame_16)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_15.addWidget(self.frame_29, 7, 0, 1, 1)
        self.frame_49 = QtWidgets.QFrame(self.frame_16)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.gridLayout_15.addWidget(self.frame_49, 10, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_16)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15.addWidget(self.frame_2, 3, 0, 1, 1)
        self.frame_48 = QtWidgets.QFrame(self.frame_16)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.gridLayout_15.addWidget(self.frame_48, 1, 0, 1, 1)
        self.userPasswordInput = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.userPasswordInput.setFont(font)
        self.userPasswordInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.userPasswordInput.setText("")
        self.userPasswordInput.setObjectName("userPasswordInput")
        self.gridLayout_15.addWidget(self.userPasswordInput, 4, 2, 1, 1)
        self.addUserBtn = QtWidgets.QPushButton(self.frame_16)
        self.addUserBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addUserBtn.setFont(font)
        self.addUserBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#addUserBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#addUserBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#addUserBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.addUserBtn.setObjectName("addUserBtn")
        self.gridLayout_15.addWidget(self.addUserBtn, 9, 2, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.frame_16)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 11, 0, 1, 1)
        self.deleteUserBtn = QtWidgets.QPushButton(self.frame_16)
        self.deleteUserBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deleteUserBtn.setFont(font)
        self.deleteUserBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#deleteUserBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#deleteUserBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#deleteUserBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.deleteUserBtn.setObjectName("deleteUserBtn")
        self.gridLayout_15.addWidget(self.deleteUserBtn, 13, 0, 1, 1)
        self.updateUserBtn = QtWidgets.QPushButton(self.frame_16)
        self.updateUserBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.updateUserBtn.setFont(font)
        self.updateUserBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#updateUserBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#updateUserBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#updateUserBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.updateUserBtn.setObjectName("updateUserBtn")
        self.gridLayout_15.addWidget(self.updateUserBtn, 13, 2, 1, 4)
        self.userNameInput = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.userNameInput.setFont(font)
        self.userNameInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.userNameInput.setText("")
        self.userNameInput.setObjectName("userNameInput")
        self.gridLayout_15.addWidget(self.userNameInput, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_16)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_16)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_16)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_15.addWidget(self.comboBox, 6, 2, 2, 1)
        self.showAllUsers = QtWidgets.QTableWidget(self.frame_16)
        self.showAllUsers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.showAllUsers.setObjectName("showAllUsers")
        self.showAllUsers.setColumnCount(5)
        self.showAllUsers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllUsers.setHorizontalHeaderItem(4, item)
        self.showAllUsers.horizontalHeader().setCascadingSectionResizes(False)
        self.showAllUsers.horizontalHeader().setSortIndicatorShown(False)
        self.showAllUsers.horizontalHeader().setStretchLastSection(False)
        self.showAllUsers.verticalHeader().setCascadingSectionResizes(False)
        self.showAllUsers.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_15.addWidget(self.showAllUsers, 12, 0, 1, 3)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_16)
        self.comboBox_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_6, 5, 2, 1, 1)
        self.frame_38 = QtWidgets.QFrame(self.frame_16)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.gridLayout_15.addWidget(self.frame_38, 8, 0, 1, 1)
        self.userEmail = QtWidgets.QLineEdit(self.frame_16)
        self.userEmail.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.userEmail.setFont(font)
        self.userEmail.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.userEmail.setText("")
        self.userEmail.setObjectName("userEmail")
        self.gridLayout_15.addWidget(self.userEmail, 5, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_16, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.manageStaffPage)
        self.manageRoomsPage = QtWidgets.QWidget()
        self.manageRoomsPage.setObjectName("manageRoomsPage")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.manageRoomsPage)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_14 = QtWidgets.QFrame(self.manageRoomsPage)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_51 = QtWidgets.QFrame(self.frame_17)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.gridLayout_23.addWidget(self.frame_51, 1, 0, 1, 2)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_23.addWidget(self.frame_18, 3, 0, 1, 2)
        self.frame_52 = QtWidgets.QFrame(self.frame_17)
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.gridLayout_23.addWidget(self.frame_52, 10, 0, 1, 2)
        self.frame_50 = QtWidgets.QFrame(self.frame_17)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.gridLayout_23.addWidget(self.frame_50, 12, 0, 1, 2)
        self.frame_30 = QtWidgets.QFrame(self.frame_17)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_23.addWidget(self.frame_30, 8, 0, 1, 2)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_23.addWidget(self.frame_19, 4, 1, 1, 2)
        self.occupancyLimitInput = QtWidgets.QComboBox(self.frame_17)
        self.occupancyLimitInput.setMinimumSize(QtCore.QSize(0, 40))
        self.occupancyLimitInput.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.occupancyLimitInput.setFont(font)
        self.occupancyLimitInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.occupancyLimitInput.setObjectName("occupancyLimitInput")
        self.occupancyLimitInput.addItem("")
        self.occupancyLimitInput.addItem("")
        self.occupancyLimitInput.addItem("")
        self.occupancyLimitInput.addItem("")
        self.occupancyLimitInput.addItem("")
        self.gridLayout_23.addWidget(self.occupancyLimitInput, 9, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_17)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_2.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_23.addWidget(self.comboBox_2, 8, 2, 3, 1)
        self.addRoomBtn = QtWidgets.QPushButton(self.frame_17)
        self.addRoomBtn.setMinimumSize(QtCore.QSize(200, 60))
        self.addRoomBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addRoomBtn.setFont(font)
        self.addRoomBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#addRoomBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#addRoomBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#addRoomBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.addRoomBtn.setObjectName("addRoomBtn")
        self.gridLayout_23.addWidget(self.addRoomBtn, 11, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_17)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_23.addWidget(self.label_14, 13, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_17)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_23.addWidget(self.label_15, 2, 0, 1, 1)
        self.roomTypeInput = QtWidgets.QComboBox(self.frame_17)
        self.roomTypeInput.setMinimumSize(QtCore.QSize(0, 40))
        self.roomTypeInput.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.roomTypeInput.setFont(font)
        self.roomTypeInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.roomTypeInput.setObjectName("roomTypeInput")
        self.roomTypeInput.addItem("")
        self.roomTypeInput.addItem("")
        self.roomTypeInput.addItem("")
        self.gridLayout_23.addWidget(self.roomTypeInput, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_23.addWidget(self.label_6, 0, 0, 1, 1)
        self.deleteRoomBtn = QtWidgets.QPushButton(self.frame_17)
        self.deleteRoomBtn.setMinimumSize(QtCore.QSize(200, 60))
        self.deleteRoomBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deleteRoomBtn.setFont(font)
        self.deleteRoomBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#deleteRoomBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#deleteRoomBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#deleteRoomBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.deleteRoomBtn.setObjectName("deleteRoomBtn")
        self.gridLayout_23.addWidget(self.deleteRoomBtn, 15, 0, 1, 1)
        self.updateRoomBtn = QtWidgets.QPushButton(self.frame_17)
        self.updateRoomBtn.setMinimumSize(QtCore.QSize(0, 60))
        self.updateRoomBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.updateRoomBtn.setFont(font)
        self.updateRoomBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#updateRoomBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#updateRoomBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#updateRoomBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.updateRoomBtn.setObjectName("updateRoomBtn")
        self.gridLayout_23.addWidget(self.updateRoomBtn, 15, 2, 1, 1)
        self.roomNoInput = QtWidgets.QLineEdit(self.frame_17)
        self.roomNoInput.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.roomNoInput.setFont(font)
        self.roomNoInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.roomNoInput.setText("")
        self.roomNoInput.setObjectName("roomNoInput")
        self.gridLayout_23.addWidget(self.roomNoInput, 5, 0, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.frame_17)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_23.addWidget(self.frame_25, 6, 0, 1, 1)
        self.allRoomsTable = QtWidgets.QTableWidget(self.frame_17)
        self.allRoomsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.allRoomsTable.setObjectName("allRoomsTable")
        self.allRoomsTable.setColumnCount(5)
        self.allRoomsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allRoomsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allRoomsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allRoomsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allRoomsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.allRoomsTable.setHorizontalHeaderItem(4, item)
        self.allRoomsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.allRoomsTable.horizontalHeader().setSortIndicatorShown(False)
        self.allRoomsTable.horizontalHeader().setStretchLastSection(False)
        self.allRoomsTable.verticalHeader().setCascadingSectionResizes(False)
        self.allRoomsTable.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_23.addWidget(self.allRoomsTable, 14, 0, 1, 3)
        self.gridLayout_22.addWidget(self.frame_17, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_14, 0, 0, 2, 2)
        self.stackedWidget.addWidget(self.manageRoomsPage)
        self.manageDatabaseBackupPage = QtWidgets.QWidget()
        self.manageDatabaseBackupPage.setObjectName("manageDatabaseBackupPage")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.manageDatabaseBackupPage)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_20 = QtWidgets.QFrame(self.manageDatabaseBackupPage)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_23 = QtWidgets.QFrame(self.frame_20)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_17.addWidget(self.frame_23, 5, 0, 1, 2)
        self.frame_32 = QtWidgets.QFrame(self.frame_20)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_32)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_17.addWidget(self.frame_32, 4, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.frame_24 = QtWidgets.QFrame(self.frame_20)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.backupDatabaseBtn = QtWidgets.QPushButton(self.frame_24)
        self.backupDatabaseBtn.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.backupDatabaseBtn.setFont(font)
        self.backupDatabaseBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#backupDatabaseBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#backupDatabaseBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#backupDatabaseBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.backupDatabaseBtn.setObjectName("backupDatabaseBtn")
        self.gridLayout_16.addWidget(self.backupDatabaseBtn, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_17.addWidget(self.frame_24, 3, 0, 1, 2)
        self.frame_33 = QtWidgets.QFrame(self.frame_20)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.gridLayout_17.addWidget(self.frame_33, 6, 0, 1, 2)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_17.addWidget(self.frame_21, 1, 0, 1, 2)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_17.addWidget(self.frame_22, 2, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.frame_20)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_17.addWidget(self.label_17, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_20, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.manageDatabaseBackupPage)
        self.manageServicePage = QtWidgets.QWidget()
        self.manageServicePage.setObjectName("manageServicePage")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.manageServicePage)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.frame_67 = QtWidgets.QFrame(self.manageServicePage)
        self.frame_67.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_67.setObjectName("frame_67")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_67)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_40 = QtWidgets.QLabel(self.frame_67)
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_20.addWidget(self.label_40, 2, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_67)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_20.addWidget(self.label_38, 0, 0, 1, 1)
        self.serviceNameInput = QtWidgets.QLineEdit(self.frame_67)
        self.serviceNameInput.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.serviceNameInput.setFont(font)
        self.serviceNameInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.serviceNameInput.setText("")
        self.serviceNameInput.setObjectName("serviceNameInput")
        self.gridLayout_20.addWidget(self.serviceNameInput, 4, 0, 1, 1)
        self.serviceDescriptionInput = QtWidgets.QTextEdit(self.frame_67)
        self.serviceDescriptionInput.setMaximumSize(QtCore.QSize(500, 16777215))
        self.serviceDescriptionInput.setObjectName("serviceDescriptionInput")
        self.gridLayout_20.addWidget(self.serviceDescriptionInput, 6, 0, 1, 1)
        self.servicePriceInput = QtWidgets.QLineEdit(self.frame_67)
        self.servicePriceInput.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.servicePriceInput.setFont(font)
        self.servicePriceInput.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.servicePriceInput.setText("")
        self.servicePriceInput.setObjectName("servicePriceInput")
        self.gridLayout_20.addWidget(self.servicePriceInput, 9, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frame_67)
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_20.addWidget(self.label_41, 12, 0, 1, 1)
        self.showAllServicesTable = QtWidgets.QTableWidget(self.frame_67)
        self.showAllServicesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.showAllServicesTable.setObjectName("showAllServicesTable")
        self.showAllServicesTable.setColumnCount(4)
        self.showAllServicesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.showAllServicesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllServicesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllServicesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showAllServicesTable.setHorizontalHeaderItem(3, item)
        self.showAllServicesTable.horizontalHeader().setCascadingSectionResizes(False)
        self.showAllServicesTable.horizontalHeader().setSortIndicatorShown(False)
        self.showAllServicesTable.horizontalHeader().setStretchLastSection(False)
        self.showAllServicesTable.verticalHeader().setCascadingSectionResizes(False)
        self.showAllServicesTable.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_20.addWidget(self.showAllServicesTable, 13, 0, 1, 2)
        self.deleteServiceBtn = QtWidgets.QPushButton(self.frame_67)
        self.deleteServiceBtn.setMinimumSize(QtCore.QSize(0, 60))
        self.deleteServiceBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deleteServiceBtn.setFont(font)
        self.deleteServiceBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#deleteServiceBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#deleteServiceBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#deleteServiceBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.deleteServiceBtn.setObjectName("deleteServiceBtn")
        self.gridLayout_20.addWidget(self.deleteServiceBtn, 14, 0, 1, 1)
        self.updateServiceBtn = QtWidgets.QPushButton(self.frame_67)
        self.updateServiceBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.updateServiceBtn.setFont(font)
        self.updateServiceBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#updateServiceBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#updateServiceBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#updateServiceBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.updateServiceBtn.setObjectName("updateServiceBtn")
        self.gridLayout_20.addWidget(self.updateServiceBtn, 14, 1, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.frame_67)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_20.addWidget(self.frame_31, 6, 1, 1, 1)
        self.frame_72 = QtWidgets.QFrame(self.frame_67)
        self.frame_72.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_72.setObjectName("frame_72")
        self.gridLayout_20.addWidget(self.frame_72, 5, 1, 1, 1)
        self.frame_68 = QtWidgets.QFrame(self.frame_67)
        self.frame_68.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_68.setObjectName("frame_68")
        self.gridLayout_20.addWidget(self.frame_68, 3, 0, 1, 1)
        self.frame_69 = QtWidgets.QFrame(self.frame_67)
        self.frame_69.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_69.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_69.setObjectName("frame_69")
        self.gridLayout_20.addWidget(self.frame_69, 1, 0, 1, 1)
        self.frame_71 = QtWidgets.QFrame(self.frame_67)
        self.frame_71.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_71.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_71.setObjectName("frame_71")
        self.gridLayout_20.addWidget(self.frame_71, 7, 0, 1, 1)
        self.frame_70 = QtWidgets.QFrame(self.frame_67)
        self.frame_70.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_70.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_70.setObjectName("frame_70")
        self.gridLayout_20.addWidget(self.frame_70, 11, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.frame_67)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_81 = QtWidgets.QFrame(self.frame_26)
        self.frame_81.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_81.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_81.setObjectName("frame_81")
        self.gridLayout_24.addWidget(self.frame_81, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame_26, 9, 1, 1, 1)
        self.frame_34 = QtWidgets.QFrame(self.frame_67)
        self.frame_34.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_20.addWidget(self.frame_34, 5, 0, 1, 1)
        self.addServiceBtn_2 = QtWidgets.QPushButton(self.frame_67)
        self.addServiceBtn_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addServiceBtn_2.setFont(font)
        self.addServiceBtn_2.setStyleSheet("/* Normal state styling */\n"
"QPushButton#addServiceBtn_2 {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#addServiceBtn_2:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#addServiceBtn_2:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.addServiceBtn_2.setObjectName("addServiceBtn_2")
        self.gridLayout_20.addWidget(self.addServiceBtn_2, 11, 1, 1, 1)
        self.frame_82 = QtWidgets.QFrame(self.frame_67)
        self.frame_82.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_82.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_82.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_82.setObjectName("frame_82")
        self.gridLayout_20.addWidget(self.frame_82, 10, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_67, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.manageServicePage)
        self.userProfile = QtWidgets.QWidget()
        self.userProfile.setObjectName("userProfile")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.userProfile)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_39 = QtWidgets.QFrame(self.userProfile)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame_39)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.frame_45 = QtWidgets.QFrame(self.frame_39)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.gridLayout_33.addWidget(self.frame_45, 1, 0, 1, 2)
        self.frame_42 = QtWidgets.QFrame(self.frame_39)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.gridLayout_33.addWidget(self.frame_42, 7, 1, 1, 1)
        self.frame_46 = QtWidgets.QFrame(self.frame_39)
        self.frame_46.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.gridLayout_33.addWidget(self.frame_46, 3, 1, 1, 1)
        self.frame_43 = QtWidgets.QFrame(self.frame_39)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.gridLayout_33.addWidget(self.frame_43, 4, 2, 1, 1)
        self.frame_41 = QtWidgets.QFrame(self.frame_39)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.gridLayout_33.addWidget(self.frame_41, 0, 2, 1, 1)
        self.frame_44 = QtWidgets.QFrame(self.frame_39)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.gridLayout_33.addWidget(self.frame_44, 2, 0, 5, 1)
        self.userProfileName = QtWidgets.QLineEdit(self.frame_39)
        self.userProfileName.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.userProfileName.setFont(font)
        self.userProfileName.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.userProfileName.setText("")
        self.userProfileName.setObjectName("userProfileName")
        self.gridLayout_33.addWidget(self.userProfileName, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_39)
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_33.addWidget(self.label_35, 0, 0, 1, 2)
        self.userProfilePassword = QtWidgets.QLineEdit(self.frame_39)
        self.userProfilePassword.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.userProfilePassword.setFont(font)
        self.userProfilePassword.setStyleSheet("border:none;\n"
"border-bottom:2px solid black;")
        self.userProfilePassword.setText("")
        self.userProfilePassword.setObjectName("userProfilePassword")
        self.gridLayout_33.addWidget(self.userProfilePassword, 4, 1, 1, 1)
        self.updateProfileBtn = QtWidgets.QPushButton(self.frame_39)
        self.updateProfileBtn.setMinimumSize(QtCore.QSize(0, 60))
        self.updateProfileBtn.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.updateProfileBtn.setFont(font)
        self.updateProfileBtn.setStyleSheet("/* Normal state styling */\n"
"QPushButton#updateProfileBtn {\n"
"    color: white;\n"
"    background: #0BDABF;\n"
"    border: 2px solid #0BDABF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover state styling */\n"
"QPushButton#updateProfileBtn:hover {\n"
"    background: #08A79D; /* Change the color for hover effect */\n"
"}\n"
"\n"
"/* Advanced styling */\n"
"QPushButton#updateProfileBtn:pressed {\n"
"    background: #067267; /* Change the color for pressed effect */\n"
"    border: 2px solid #067267;\n"
"}\n"
"\n"
"/* Add any other advanced styling here */\n"
"\n"
"")
        self.updateProfileBtn.setObjectName("updateProfileBtn")
        self.gridLayout_33.addWidget(self.updateProfileBtn, 6, 1, 1, 1)
        self.frame_47 = QtWidgets.QFrame(self.frame_39)
        self.frame_47.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.gridLayout_33.addWidget(self.frame_47, 5, 1, 1, 1)
        self.gridLayout_21.addWidget(self.frame_39, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.userProfile)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.navBar.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Inn\n"
"Sync"))
        self.label_3.setText(_translate("MainWindow", "Dashboard"))
        self.totla_users_label.setText(_translate("MainWindow", "750"))
        self.label_9.setText(_translate("MainWindow", "Amount of residents"))
        self.label_10.setText(_translate("MainWindow", "Available Rooms"))
        self.label_13.setText(_translate("MainWindow", "500"))
        self.label_11.setText(_translate("MainWindow", "Kicked Users"))
        self.label_12.setText(_translate("MainWindow", "150"))
        self.label_4.setText(_translate("MainWindow", "Market Place"))
        self.label_51.setText(_translate("MainWindow", "Worst Selling"))
        self.label_53.setText(_translate("MainWindow", "312"))
        self.label_50.setText(_translate("MainWindow", "Best Selling"))
        self.label_43.setText(_translate("MainWindow", "Sunday"))
        self.label_52.setText(_translate("MainWindow", "Friday"))
        self.label_54.setText(_translate("MainWindow", "123"))
        self.label_45.setText(_translate("MainWindow", "Sales"))
        self.label_18.setText(_translate("MainWindow", "Calculated in last 7 days"))
        self.label_56.setText(_translate("MainWindow", "Worst Selling"))
        self.label_55.setText(_translate("MainWindow", "Worst Selling"))
        self.label_34.setText(_translate("MainWindow", "All Feedbacks:"))
        self.label_32.setText(_translate("MainWindow", "Guest Feedbacks"))
        item = self.showAllUsersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.showAllUsersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.showAllUsersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.showAllUsersTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Feedback"))
        self.addUserBtn.setText(_translate("MainWindow", "Add User"))
        self.label_8.setText(_translate("MainWindow", "All Users"))
        self.deleteUserBtn.setText(_translate("MainWindow", "Delete"))
        self.updateUserBtn.setText(_translate("MainWindow", "Update"))
        self.label_7.setText(_translate("MainWindow", "Add Users:"))
        self.label_5.setText(_translate("MainWindow", "Manage Users"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Role"))
        item = self.showAllUsers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.showAllUsers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Room No"))
        item = self.showAllUsers.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Room Type"))
        item = self.showAllUsers.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Occupancy"))
        item = self.showAllUsers.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Availability"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Guest"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Manager"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Front Desk"))
        self.occupancyLimitInput.setItemText(0, _translate("MainWindow", "Occupency Limit"))
        self.occupancyLimitInput.setItemText(1, _translate("MainWindow", "1"))
        self.occupancyLimitInput.setItemText(2, _translate("MainWindow", "2"))
        self.occupancyLimitInput.setItemText(3, _translate("MainWindow", "3"))
        self.occupancyLimitInput.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Role"))
        self.addRoomBtn.setText(_translate("MainWindow", "Add Room"))
        self.label_14.setText(_translate("MainWindow", "All Rooms"))
        self.label_15.setText(_translate("MainWindow", "Add Room:"))
        self.roomTypeInput.setItemText(0, _translate("MainWindow", "Room Type"))
        self.roomTypeInput.setItemText(1, _translate("MainWindow", "Single Room"))
        self.roomTypeInput.setItemText(2, _translate("MainWindow", "Double Room"))
        self.label_6.setText(_translate("MainWindow", "Manage Rooms"))
        self.deleteRoomBtn.setText(_translate("MainWindow", "Delete"))
        self.updateRoomBtn.setText(_translate("MainWindow", "Update"))
        item = self.allRoomsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.allRoomsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.allRoomsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.allRoomsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Password"))
        item = self.allRoomsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Role"))
        self.backupDatabaseBtn.setText(_translate("MainWindow", "Backup Database"))
        self.label_17.setText(_translate("MainWindow", "Database Backup"))
        self.label_40.setText(_translate("MainWindow", "Add Service"))
        self.label_38.setText(_translate("MainWindow", "Manage Services"))
        self.label_41.setText(_translate("MainWindow", "All Services"))
        item = self.showAllServicesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.showAllServicesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Service Name"))
        item = self.showAllServicesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Service Details"))
        item = self.showAllServicesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.deleteServiceBtn.setText(_translate("MainWindow", "Delete"))
        self.updateServiceBtn.setText(_translate("MainWindow", "Update"))
        self.addServiceBtn_2.setText(_translate("MainWindow", "Add Service"))
        self.label_35.setText(_translate("MainWindow", "User Profile"))
        self.updateProfileBtn.setText(_translate("MainWindow", "Update Profile"))
import resource_rc
